### ISSUE TITLE
Having problems integrating vowsjs/vows and older versions of coffee-script < 1.7.0

### ISSUE THREAD

**Issue by silkentrance** [tkellen/node-interpret#13]
Requirement: needs to be orchestrated with tkellen/node-rechoir#14

I am currently trying to integrate node-rechoir into vows. While this actually works like a charm *kudos* for coffee-script 1.8.0, it is also a pain in the *** for versions below 1.7.0.

Older versions of coffee-script do not have a coffee-script/register module. In fact, they will register themselves automatically.

Since node-interpret only supports coffee-script versions with a register module, I am stuck as I would like node-rechoir/node-interpret to support coffee-script and its derivates, most prominently iced-coffee-script, out of the box without me having to use a custom node-interpret to override the existing declarations for the available coffee-script/iced-coffee-script extensions.

What I'd like to have is that node-interpret takes care of this rather common issue and that I will not have to include a custom node-interpret.js with any of my legacy projects. The same goes for others as well, who are still stuck with version 1.6.2 of coffee-script.

I have come up with a solution to this problem, however, it requires changes to both node-interpret and node-rechoir. And such was actually the reason for proposing #12 in order to get rid of the central registry of supported languages in the first place... but never mind.

Please have a look at the upcoming PRs for both node-rechoir and node-interpret and see how it fits into your plans for both packages.

**Comment by phated** [comment]
This was fixed with https://github.com/tkellen/node-interpret/commit/f186ea6a48655514763de22acc0ca2292ce2f3f1 - at least how it relates to `interpret`
