### ISSUE TITLE
Support es6 based on the .es6 extension

### ISSUE THREAD

**Issue by phated** [tkellen/node-interpret#8]
This can easily be done with https://6to5.org/usage.html#require-hook but it would register as `.js` also. Opening another issue to allow configuration objects to solve this.

**Comment by silkentrance** [comment]
@phated I see where this is going to. Well, for one thing, node-interpret does not require the external modules, node-rechoir does. It will require the module, say require("6to5/register"). This in turn will return a function R, that when called will expect the user to provide a configuration object.

This function will then be passed on, as the module parameter, to whatever registration function is defined for the module '6to5/register'.

In there, you would want your configuration object to be passed to function R.

**Comment by silkentrance** [comment]
@phated, @tkellen 

I have create a patch for both node-interpret and test cases for node-rechoir.

Check out vibejs/node-rechoir@8ec6edcd210b144eebc108138b19df0491256475

Please note that this version of node-rechoir expects you to pass in the requiring module, see tkellen/node-rechoir#10 for more information.

**Comment by phated** [comment]
@tkellen what are your thoughts on letting 6to5 register on `.js` if it is loaded, but only load on `.es6`?  e.g. if your gulpfile is named `gulpfile.es6` then 6to5 will be required and hook into `.js` and `.es6` so you don't need to name all your files `.es6`

**Comment by tkellen** [comment]
`+1`

**Comment by phated** [comment]
Added tests in rechoir for es6 - https://github.com/tkellen/node-rechoir/commit/e80518c8a0de140eec206d3e3c76857cb486f40e
