### ISSUE TITLE
Support configuration objects

### ISSUE THREAD

**Issue by phated** [tkellen/node-interpret#9]
Supporting es6 through 6to5 requires a config object that sets extensions (to avoid `.js` collisions).  Add support for this before #8.

**Comment by silkentrance** [comment]
@phated have you look at the registration function for node-jsx? It will pass a configuration object to the register function for that language.

**Comment by phated** [comment]
Based on the discussion in #13, I think the most basic config object should be something like:

```js
{
    module: 'coffee-script/register',
    legacyModules: ['coffee-script'], // should we make this support an array or string? I think the array is important to support languages that have changed more than once
    options: {} // config object to be passed to executed function
}
```

**Comment by silkentrance** [comment]
And this configuration object comes from where? Is it part of node-interpret or can the user pass in that kind of configuration?

**Comment by phated** [comment]
It's built into this library. The need comes from 6to5 registering on `.js` extension

**Comment by silkentrance** [comment]
And what about different "legacy modules" requiring different options?
I'd propose the following

```
   {
        'coffee-script' : {
             '<1.7.0' : { // no options, no special cases
                 extensions: ['.coffee', ...]
            }, 
             '>1.7.0' : {
                  require : 'coffee-script/register'.
                 extensions: ['.coffee', '.litcoffee', '.coffee.md']
             }
        }
        '6to5': {
              '...' : {
                   require : '6to5/register'
                   extensions : ['.es6', '.js6']
                   options : {
                      extensions: ['.es6', '.js6']
                   }
              }
        }
   }
```

How about this instead?

**Comment by phated** [comment]
you are inverting the `extension: module` paradigm and I don't think that fits as much.  node-rechoir doesn't check versions first and I don't think it makes sense to

**Comment by silkentrance** [comment]
Actually, the extensions : module paradigm still exists. The module is then used for looking it up in the version specs, along with the extension. If a match can be found, then the configuration for that version spec will be used.

**Comment by phated** [comment]
This was closed by https://github.com/tkellen/node-interpret/commit/f186ea6a48655514763de22acc0ca2292ce2f3f1
